CREATE TABLE RitualUrn (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL UNIQUE,
    Price REAL NOT NULL CHECK(Price > 0),
    ImagePath TEXT NOT NULL
);

CREATE TABLE Corpose (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    Surname TEXT NOT NULL,
    NumPassport TEXT NOT NULL UNIQUE CHECK(LENGTH(NumPassport)=14)
);

CREATE TABLE Hall (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Capacity INTEGER NOT NULL CHECK(Capacity > 0),
    Price REAL NOT NULL CHECK(Price > 0)
);

CREATE TABLE Dates(
    HallId INTEGER NOT NULL,
    FOREIGN KEY (HallId)  REFERENCES Hall (Id) ON DELETE CASCADE,
    Date TEXT NOT NULL,
    PRIMARY KEY (HallId, Date)
);

CREATE TABLE Coffin (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL UNIQUE,
    Price REAL NOT NULL CHECK(Price > 0),
    ImagePath TEXT NOT NULL
);

CREATE TABLE Ceremony(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Contact TEXT NOT NULL,
    NameOfCompany TEXT NOT NULL,
    Description TEXT NOT NULL
);

CREATE TABLE StateOrder(
    Code INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL
);

CREATE TABLE Role(
    Code INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL
);

CREATE TABLE User(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    Surname TEXT NOT NULL,
    EmailAdress TEXT NOT NULL,
    RoleCode INTEGER,
    NumPassport TEXT NOT NULL UNIQUE CHECK(LENGTH(NumPassport)=14),
    FOREIGN KEY (RoleCode) REFERENCES Role(Code) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS NameNumPassport ON User (Name, NumPassport)

CREATE TABLE Orders(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    DateOfActual TEXT NOT NULL,
    HallId INTEGER,
    CorposeId INTEGER,
    CoffinId INTEGER,
    UserId INTEGER,
    UrnId INTEGER,
    StateCode INTEGER,
    FOREIGN KEY (HallId) REFERENCES Hall(Id) ON DELETE SET NULL,
    FOREIGN KEY (CorposeId) REFERENCES Corpose(Id) ON DELETE SET NULL,
    FOREIGN KEY (CoffinId) REFERENCES Coffin(Id) ON DELETE SET NULL,
    FOREIGN KEY (UserId) REFERENCES User(Id) ON DELETE SET NULL,
    FOREIGN KEY (UrnId) REFERENCES RitualUrn(Id) ON DELETE SET NULL,
    FOREIGN KEY (StateCode) REFERENCES StateOrder(Code) ON DELETE SET NULL
);

CREATE TABLE OrderCeremony (
    OrderId INTEGER,
    CeremonyId INTEGER,
    FOREIGN KEY (OrderId) REFERENCES Orders(Id) ON DELETE CASCADE,
    FOREIGN KEY (CeremonyId) REFERENCES Ceremony(Id) ON DELETE CASCADE
);