CREATE TABLE RitualUrn (
    Id SERIAL PRIMARY KEY,
    Name CHARACTER VARYING(20) NOT NULL UNIQUE,
    Price NUMERIC(8, 2) NOT NULL CHECK(Price > 0),
    ImagePath TEXT NOT NULL
);

CREATE TABLE Corpose (
    Id SERIAL PRIMARY KEY,
    Name CHARACTER VARYING(20) NOT NULL,
    Surname CHARACTER VARYING(20) NOT NULL,
    NumPassport CHAR(14) NOT NULL UNIQUE
);

CREATE TABLE Hall (
    Id SERIAL PRIMARY KEY,
    Capacity INTEGER NOT NULL CHECK(Capacity > 0),
    Price NUMERIC(8, 2) NOT NULL CHECK(Price > 0)
);

CREATE TABLE Dates(
    HallId INTEGER NOT NULL,
    FOREIGN KEY (HallId)  REFERENCES Hall (Id) ON DELETE CASCADE,
    Date DATE NOT NULL,
    PRIMARY KEY (HallId, Date)
);

CREATE TABLE Coffin (
    Id SERIAL PRIMARY KEY,
    Name CHARACTER VARYING(20) NOT NULL UNIQUE,
    Price NUMERIC(8, 2) NOT NULL CHECK(Price > 0),
    ImagePath TEXT NOT NULL
);

CREATE TABLE Ceremony(
    Id SERIAL PRIMARY KEY,
    Contact TEXT NOT NULL,
    NameOfCompany TEXT NOT NULL,
    Description TEXT NOT NULL
);

CREATE TABLE StateOrder(
    Code SERIAL PRIMARY KEY,
    Name CHARACTER VARYING(20) NOT NULL
);

CREATE TABLE Role(
    Code SERIAL PRIMARY KEY,
    Name CHARACTER VARYING(20) NOT NULL
);

CREATE TABLE Users(
    Id SERIAL PRIMARY KEY,
    Name CHARACTER VARYING(20) NOT NULL,
    Surname CHARACTER VARYING(20) NOT NULL,
    EmailAdress TEXT NOT NULL,
    RoleCode INTEGER,
    NumPassport CHAR(14) NOT NULL UNIQUE,
    FOREIGN KEY (RoleCode) REFERENCES Role(Code) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS NameNumPassport ON Users (Name, NumPassport)

CREATE TABLE Orders(
    Id SERIAL PRIMARY KEY,
    DateOfActual DATE NOT NULL,
    HallId INTEGER,
    CorposeId INTEGER,
    CoffinId INTEGER,
    UserId INTEGER,
    UrnId INTEGER,
    StateCode INTEGER,
    FOREIGN KEY (HallId) REFERENCES Hall(Id) ON DELETE SET NULL,
    FOREIGN KEY (CorposeId) REFERENCES Corpose(Id) ON DELETE SET NULL,
    FOREIGN KEY (CoffinId) REFERENCES Coffin(Id) ON DELETE SET NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE SET NULL,
    FOREIGN KEY (UrnId) REFERENCES RitualUrn(Id) ON DELETE SET NULL,
    FOREIGN KEY (StateCode) REFERENCES StateOrder(Code) ON DELETE SET NULL
);

CREATE TABLE OrderCeremony (
    OrderId INTEGER,
    CeremonyId INTEGER,
    FOREIGN KEY (OrderId) REFERENCES Orders(Id) ON DELETE CASCADE,
    FOREIGN KEY (CeremonyId) REFERENCES Ceremony(Id) ON DELETE CASCADE
);

CREATE TABLE OrdersAudit (
    Operation CHAR(1) NOT NULL,
    Stamp TIMESTAMP NOT Null,
    OrderId INTEGER,
    ClientNumPassport CHAR(14) NOT NULL
);